### ISSUE TITLE
Extensions EIP712: a few improvements

### ISSUE THREAD

**Issue by carletex** [scaffold-eth/create-eth-extensions#4]
- [x] Same text size on input / textarea
![image](https://github.com/scaffold-eth/create-eth-extensions/assets/2486142/d3e0b83b-139c-4d88-84c7-20560b94c7e0)

- [x] Loading button / spinner when sending the request (specially backend)

- [x] Have some info about EIP 712 in the page (a paragraph with a small description and a link to https://eips.ethereum.org/EIPS/eip-712 and hinting to check the `eip-712/page.tsx`). We can tinker in the PR (deciding the text, etc)

**Comment by technophile-04** [comment]
Ohh while testing https://github.com/scaffold-eth/create-eth/pull/57 noticed that the prettier formatting for this two file is not correct: 
![Screenshot 2024-06-20 at 12 22 01 AM](https://github.com/scaffold-eth/create-eth-extensions/assets/80153681/bce3cabb-8222-4d9b-aee0-b46dd90e7822)


maybe @rin-st, you could do `npx create-eth@latest -e eip-712` create an instance copy paste its formatting to this repo extension files

**Comment by rin-st** [comment]
Thanks! Updated it [ded3f2a](https://github.com/scaffold-eth/create-eth-extensions/commit/ded3f2ad3f11f33b227b88a0b8ed7259f479c265)

As I understand formatting inside extension does not matter since everything is formatted when creating instance? Am I missing something?

And if we need the same formatting in extension as in `create-eth`, we need the same prettier rules as in `create-eth` folder.

https://github.com/scaffold-eth/create-eth/pull/57 solves this problem but I think we need to remember that if someone will create extensions other way, formatting most likely will be different

**Comment by technophile-04** [comment]
> As I understand formatting inside extension does not matter since everything is formatted when creating instance? Am I missing something?

Ohh yes! there is no problem here(while consuming the extension through npx create-eth@latest)

But when you are testing extension, in this case while I was testing `eip-712` extension: 

1. Clone this extension in `externalExtensions` dir of `create-eth` repo : 

   ```shell
   git clone https://github.com/scaffold-eth/create-eth-extensions.git eip-712 -b test-712
   ```
2. Now when I run : 
   ```shell
   yarn cli ../test-blah -e test-712 -s hardhat -i
   ```
   
Since the cloned extension is symlinked with instance created, and the created instance code was formatted afterwards, hence I got the diff in extension since orignally extension code was not formatted. 

But nevertheless you fixed it at https://github.com/scaffold-eth/create-eth-extensions/commit/ded3f2ad3f11f33b227b88a0b8ed7259f479c265

> but I think we need to remember that if someone will create extensions other way, formatting most likely will be different

Yeah I agree! but I think we should tell people to use this `create-eth` repo while creating / testing extensio to use `create-eth` repo and avoid doing changes to their extensions directly, instead use symlinked instance to do the changes

**Comment by rin-st** [comment]
Thank you for detailed explanation, Shiv! 🙏  I tried the same but without cloning, just copypasted, so I didn't see the diff

> Yeah I agree! but I think we should tell people to use this create-eth repo while creating / testing extensio to use create-eth repo and avoid doing changes to their extensions directly, instead use symlinked instance to do the changes

Yes! 👍

**Comment by rin-st** [comment]
Closing this since improvements added. Thank you guys!
